version: '3.8'

services:
  apache:
    build: .                   # 改为 build，而非 image
    container_name: apache-php
    ports:
      - "8090:80"
    volumes:
      - /Users/alexlueng/Code/work/frtbio:/var/www/html
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge