CREATE TABLE projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_name VARCHAR(255),
    contract_number VARCHAR(100),
    tender_number VARCHAR(100),
    project_type VARCHAR(100),
    p_serial_number VARCHAR(100),
    l_serial_number VARCHAR(100),
    f_serial_number VARCHAR(100),
    purchaser VARCHAR(255),
    company_b_name VARCHAR(255),
    company_c_name VARCHAR(255),
    company_d_name VARCHAR(255),
    a1 TINYINT(1),
    a2 TINYINT(1),
    b3 TINYINT(1),
    b4 TINYINT(1),
    b5 TINYINT(1),
    b6 TINYINT(1),
    c7 TINYINT(1),
    c8 TINYINT(1),
    c9 TINYINT(1),
    c10 TINYINT(1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);